type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

left_wheel: "left_wheel_joint"
right_wheel: "right_wheel_joint"

wheel_separation: 0.2

# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
#pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
#twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
pose_covariance_diagonal: [0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
twist_covariance_diagonal: [0.000, 0.000, 0.000, 0.000, 0.000, 0.000]

# Top level frame (link) of the robot description
#base_frame_id: base_link
base_frame_id: base_footprint

# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 1.0   # m/s          0.7
    has_acceleration_limits: true
    max_acceleration       : 1.0   # m/s^2	  1.0
angular:
  z:
    has_velocity_limiEs    : true
    max_velocity           : 3.0   # rad/s        2.0
    has_acceleration_limits: true
    max_acceleration       : 2.0   # rad/s^2      6.0

# [BETA] testing PID gains 
/gazebo_ros_control:
  pid_gains:
    left_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
